version: "3"

services:
  # Database
  db:
    image: mysql:5.7
    volumes:
      - ./data:/docker-entrypoint-initdb.d # where to find our data -- we'll talk more about this
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PW}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PW}"

  #phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80" #8000 on local machine maps to 80 on the container
    environment:
      PMA_HOST: DB
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PW}"
      UPLOAD_LIMIT: 300M

    #before adding phpMyadmin, we need to map the volume of db_data and the network of wp_site

  wordpress: # name of our wordpress container
    depends_on: # container dependencies that need to be running first
      - db
    image: wordpress:latest # image used by our container
    ports:
      - "8000:80" # setting our ports for networking
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306 # default mysql port
      WORDPRESS_DB_NAME: "${DB_NAME}"
      WORDPRESS_DB_USER: "${DB_USER}"
      WORDPRESS_DB_PASSWORD: "${DB_PW}" # matches the password set in the db container
    volumes:
      - ./wp-content/themes:/var/www/html/wp-content/themes # mapping our themes to the container
      - ./wp-content/plugins:/var/www/html/wp-content/plugins # map our plugins to the container
      - ./wp-content/uploads:/var/www/html/wp-content/uploads # map our uploads to the container
